CREATE TABLE rentals (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    bookId BIGINT,
    userId BIGINT,
    rentalDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    returnDeadline DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL 7 DAY,
    returnDate DATETIME,
    FOREIGN KEY (bookId) REFERENCES books(id),
    FOREIGN KEY (userId) REFERENCES users(id)
);
